name: AOSP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: cimg/deploy:2025.01
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build AOSP
        run: |
          cd $GITHUB_WORKSPACE
          sudo bash cirrus-after.sh

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/out/*
          name: Afterlife-"$(date +"%Y%m%d")"
          tag_name: ${{ github.run_id }}
          repository: XeroRelease
          body: |
            Always Mewing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
